-- Migration: create_core_tables
-- Phase 1 Foundation: profiles, searches, contacts, outreach, guest_ip_limits
-- RLS policies enforce row-level data isolation via auth.uid() (Supabase PostgreSQL)
-- See: .planning/phases/01-foundation/01-RESEARCH.md Pattern 2

-- ============================================
-- CREATE TABLES (Prisma-generated DDL)
-- ============================================

-- profiles: 1:1 with Supabase auth.users
-- Auto-populated via handle_new_user trigger (see bottom of migration)
CREATE TABLE "profiles" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "full_name" TEXT,
    "avatar_url" TEXT,
    "plan" TEXT NOT NULL DEFAULT 'free',
    "stripe_customer_id" TEXT,
    "stripe_subscription_id" TEXT,
    "searches_used_this_month" INTEGER NOT NULL DEFAULT 0,
    "drafts_used_this_month" INTEGER NOT NULL DEFAULT 0,
    "searches_reset_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "profiles_pkey" PRIMARY KEY ("id")
);

-- searches: supports both authenticated and guest (userId nullable)
CREATE TABLE "searches" (
    "id" TEXT NOT NULL,
    "user_id" TEXT,
    "session_id" TEXT,
    "company" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "location" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "deleted_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "searches_pkey" PRIMARY KEY ("id")
);

-- contacts: enriched contact data linked to a search
CREATE TABLE "contacts" (
    "id" TEXT NOT NULL,
    "search_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "email" TEXT,
    "email_confidence" TEXT,
    "score" INTEGER,
    "research_background" TEXT,
    "research_ask_this" TEXT,
    "research_mention_this" TEXT,
    "source_url" TEXT,
    "pipeline_stage" TEXT NOT NULL DEFAULT 'identified',
    "notes" TEXT,
    "deleted_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "contacts_pkey" PRIMARY KEY ("id")
);

-- outreach: email drafts generated by the Email Drafter agent
CREATE TABLE "outreach" (
    "id" TEXT NOT NULL,
    "contact_id" TEXT NOT NULL,
    "template_type" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "tone" TEXT NOT NULL,
    "sent_at" TIMESTAMP(3),
    "sent_via" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "outreach_pkey" PRIMARY KEY ("id")
);

-- guest_ip_limits: daily IP-based rate limiting for unauthenticated searches (D-01)
CREATE TABLE "guest_ip_limits" (
    "id" TEXT NOT NULL,
    "ip_address" TEXT NOT NULL,
    "search_count" INTEGER NOT NULL DEFAULT 0,
    "date" DATE NOT NULL DEFAULT CURRENT_DATE,

    CONSTRAINT "guest_ip_limits_pkey" PRIMARY KEY ("id")
);

-- ============================================
-- UNIQUE CONSTRAINTS
-- ============================================

CREATE UNIQUE INDEX "profiles_user_id_key" ON "profiles"("user_id");
CREATE UNIQUE INDEX "profiles_stripe_customer_id_key" ON "profiles"("stripe_customer_id");
CREATE UNIQUE INDEX "profiles_stripe_subscription_id_key" ON "profiles"("stripe_subscription_id");
CREATE UNIQUE INDEX "guest_ip_limits_ip_address_date_key" ON "guest_ip_limits"("ip_address", "date");

-- ============================================
-- FOREIGN KEYS
-- ============================================

ALTER TABLE "searches" ADD CONSTRAINT "searches_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "profiles"("user_id")
    ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "contacts" ADD CONSTRAINT "contacts_search_id_fkey"
    FOREIGN KEY ("search_id") REFERENCES "searches"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "outreach" ADD CONSTRAINT "outreach_contact_id_fkey"
    FOREIGN KEY ("contact_id") REFERENCES "contacts"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- ============================================
-- ROW LEVEL SECURITY (per D-14, D-22, FOUND-04)
-- CRITICAL: Gate on profiles table, NEVER user_metadata (Pitfall 1)
-- auth.uid() is a Supabase PostgreSQL function — only works on Supabase
-- Service role key automatically bypasses RLS (no explicit policy needed for webhook handler)
-- ============================================

-- Enable RLS on all user-scoped tables
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "searches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contacts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "outreach" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "guest_ip_limits" ENABLE ROW LEVEL SECURITY;

-- profiles: users can only read/update their own profile
-- INSERT is handled by the handle_new_user trigger (auth.users creates profile automatically)
CREATE POLICY "profiles_select_own" ON "profiles"
    FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "profiles_update_own" ON "profiles"
    FOR UPDATE USING (auth.uid()::text = user_id);

-- searches: scoped to owner; guests can insert with null user_id
CREATE POLICY "searches_select_own" ON "searches"
    FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "searches_insert" ON "searches"
    FOR INSERT WITH CHECK (auth.uid()::text = user_id OR user_id IS NULL);

CREATE POLICY "searches_update_own" ON "searches"
    FOR UPDATE USING (auth.uid()::text = user_id);

-- contacts: scoped via parent search ownership
-- Guest contacts (search.user_id IS NULL) are accessible without auth
CREATE POLICY "contacts_select_own" ON "contacts"
    FOR SELECT USING (
        auth.uid()::text = (SELECT user_id FROM searches WHERE id = search_id)
    );

CREATE POLICY "contacts_insert_own" ON "contacts"
    FOR INSERT WITH CHECK (
        auth.uid()::text = (SELECT user_id FROM searches WHERE id = search_id)
        OR (SELECT user_id FROM searches WHERE id = search_id) IS NULL
    );

CREATE POLICY "contacts_update_own" ON "contacts"
    FOR UPDATE USING (
        auth.uid()::text = (SELECT user_id FROM searches WHERE id = search_id)
    );

-- outreach: scoped via contact -> search ownership chain
CREATE POLICY "outreach_select_own" ON "outreach"
    FOR SELECT USING (
        auth.uid()::text = (
            SELECT s.user_id FROM contacts c
            JOIN searches s ON s.id = c.search_id
            WHERE c.id = contact_id
        )
    );

CREATE POLICY "outreach_insert_own" ON "outreach"
    FOR INSERT WITH CHECK (
        auth.uid()::text = (
            SELECT s.user_id FROM contacts c
            JOIN searches s ON s.id = c.search_id
            WHERE c.id = contact_id
        )
    );

CREATE POLICY "outreach_update_own" ON "outreach"
    FOR UPDATE USING (
        auth.uid()::text = (
            SELECT s.user_id FROM contacts c
            JOIN searches s ON s.id = c.search_id
            WHERE c.id = contact_id
        )
    );

-- guest_ip_limits: server-side only via service role key — no user-facing policies
-- The service role key bypasses RLS automatically — anon users never query this table directly

-- ============================================
-- PROFILE AUTO-CREATION TRIGGER
-- Fires when a new user signs up via Supabase Auth (Google OAuth)
-- Creates the profiles row automatically — no client-side code needed
-- SECURITY DEFINER runs as function owner (bypasses RLS) — intentional for initial INSERT
-- ============================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.profiles (
        id,
        user_id,
        email,
        full_name,
        avatar_url,
        plan,
        searches_used_this_month,
        drafts_used_this_month,
        searches_reset_at,
        created_at,
        updated_at
    ) VALUES (
        gen_random_uuid()::text,
        NEW.id::text,
        NEW.email,
        NEW.raw_user_meta_data->>'full_name',
        NEW.raw_user_meta_data->>'avatar_url',
        'free',
        0,
        0,
        NOW(),
        NOW(),
        NOW()
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
