name: Actionlint

on:
  pull_request:
    branches: [main, develop]
    paths:
      - ".github/workflows/**"
  push:
    branches: [main, develop]
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        uses: reviewdog/actionlint@v1
        with:
          fail_level: any
